if !def(ASSETS_DEF_INC)
def ASSETS_DEF_INC equ 1

def CHAR_CLEAR_OFFSET           equ $15
def CHAR_BLACK_OFFSET           equ $3B
def CHAR_HUD_TILE_OFFSET        equ $39
def CHAR_NUMBERS_OFFSET         equ $49
def CHAR_ANTE_OFFSET            equ $47
def CHAR_ARROW_OFFSET           equ $53
def CHAR_MULTIPLIER_OFFSET      equ $54
def CHAR_DASH_SYMBOL_OFFSET     equ $57
def CHAR_CASH_SYMBOL_OFFSET     equ $55
def CHAR_DPAD_OFFSET            equ $56
def CHAR_SELECT_OFFSET          equ $37

def CHAR_LETTER_A_OFFSET        equ 42
def CHAR_LETTER_B_OFFSET        equ 43
def CHAR_LETTER_C_OFFSET        equ 44
def CHAR_LETTER_D_OFFSET        equ 45
def CHAR_LETTER_E_OFFSET        equ 46
def CHAR_LETTER_F_OFFSET        equ 47
def CHAR_LETTER_G_OFFSET        equ 48
def CHAR_LETTER_H_OFFSET        equ 49
def CHAR_LETTER_I_OFFSET        equ 50
def CHAR_LETTER_J_OFFSET        equ 51
def CHAR_LETTER_K_OFFSET        equ 52
def CHAR_LETTER_L_OFFSET        equ 53
def CHAR_LETTER_M_OFFSET        equ 54
def CHAR_LETTER_N_OFFSET        equ 58
def CHAR_LETTER_O_OFFSET        equ 73
def CHAR_LETTER_P_OFFSET        equ 60
def CHAR_LETTER_Q_OFFSET        equ 61
def CHAR_LETTER_R_OFFSET        equ 62
def CHAR_LETTER_S_OFFSET        equ 63
def CHAR_LETTER_T_OFFSET        equ 64
def CHAR_LETTER_U_OFFSET        equ 65
def CHAR_LETTER_V_OFFSET        equ 66
def CHAR_LETTER_W_OFFSET        equ 67
def CHAR_LETTER_X_OFFSET        equ 68
def CHAR_LETTER_Y_OFFSET        equ 69
def CHAR_LETTER_Z_OFFSET        equ 70

def PALETTE_HUD_HAND         equ 0
def PALETTE_HUD_CHIPS        equ 1
def PALETTE_HUD_MULT         equ 2
def PALETTE_HUD_MONEY        equ 3
def PALETTE_HUD_DEFAULT      equ 4
def PALETTE_HUD_GOAL         equ 5

endc
